/** entity parent-type → the layer/dataset toggle that renders its dots.
 *  Kind toggles ARE the datasets now (one chunk per taxonomy kind), so
 *  this is mostly identity + taxonomy synonyms. GENERATED-ish: keep in
 *  sync with taxonomy.json. Battles keep a dedicated layer. */
export const SITE_TYPE_TO_LAYER: Record<string, { show?: string; dataset?: string }> = {
  battle: { show: 'showBattles' },
  settlement: { show: 'showSettlements' },
  amphitheater: { dataset: 'amphitheater' },
  aqueduct: { dataset: 'aqueduct' },
  basilica: { dataset: 'basilica' },
  bath: { dataset: 'bath' },
  bridge: { dataset: 'bridge' },
  building: { dataset: 'building' },
  camp: { dataset: 'camp' },
  cemetery: { dataset: 'cemetery' },
  church: { dataset: 'church' },
  circus: { dataset: 'circus' },
  cistern: { dataset: 'cistern' },
  dam: { dataset: 'dam' },
  farm: { dataset: 'farm' },
  fort: { dataset: 'fort' },
  fortification: { dataset: 'fortification' },
  forum: { dataset: 'forum' },
  gate: { dataset: 'gate' },
  lighthouse: { dataset: 'lighthouse' },
  mausoleum: { dataset: 'mausoleum' },
  mine: { dataset: 'mine' },
  monastery: { dataset: 'monastery' },
  monument: { dataset: 'monument' },
  palace: { dataset: 'palace' },
  pass: { dataset: 'pass' },
  port: { dataset: 'port' },
  press: { dataset: 'press' },
  pyramid: { dataset: 'pyramid' },
  road: { dataset: 'road' },
  'road-station': { dataset: 'road-station' },
  sanctuary: { dataset: 'sanctuary' },
  shipwreck: { dataset: 'shipwreck' },
  temple: { dataset: 'temple' },
  theater: { dataset: 'theater' },
  tomb: { dataset: 'tomb' },
  townhouse: { dataset: 'townhouse' },
  tumulus: { dataset: 'tumulus' },
  villa: { dataset: 'villa' },
  wall: { dataset: 'wall' },
  watchtower: { dataset: 'watchtower' },
  workshop: { dataset: 'workshop' },
  arch: { dataset: 'monument' },
  estate: { dataset: 'villa' },
  harbour: { dataset: 'port' },
  quarry: { dataset: 'mine' },
  'religious-site': { dataset: 'sanctuary' },
  shrine: { dataset: 'sanctuary' },
  well: { dataset: 'cistern' },
  religion: { dataset: 'sanctuary' },
  religious: { dataset: 'sanctuary' },
  'legionary-fortress': { dataset: 'fort' },
}
