/** entity parent-type → the layer/dataset toggle that renders its dots.
 *  ONE source of truth, used by search (turn the layer on when a site is
 *  selected) and MonumentLabels (only label types whose dots are visible).
 *  Since the unified rework, point entities live in the entity atlas —
 *  dataset ids ARE the atlas categories (see datasetRegistry.ts); only
 *  battles and aqueduct lines keep dedicated layers. */
export const SITE_TYPE_TO_LAYER: Record<string, { show?: string; dataset?: string }> = {
  battle: { show: 'showBattles' },
  aqueduct: { show: 'showAqueducts' },
  amphitheater: { dataset: 'cities' },
  building: { dataset: 'cities' },
  theater: { dataset: 'cities' },
  townhouse: { dataset: 'rural' },
  settlement: { dataset: 'cities' },
  temple: { dataset: 'religious' },
  religion: { dataset: 'religious' },
  religious: { dataset: 'religious' },
  'religious-site': { dataset: 'religious' },
  sanctuary: { dataset: 'religious' },
  shrine: { dataset: 'religious' },
  monastery: { dataset: 'religious' },
  church: { dataset: 'religious' },
  villa: { dataset: 'rural' },
  estate: { dataset: 'rural' },
  farm: { dataset: 'rural' },
  fort: { dataset: 'military' },
  cemetery: { dataset: 'funerary' },
  tomb: { dataset: 'funerary' },
  tumulus: { dataset: 'funerary' },
  pyramid: { dataset: 'funerary' },
  mausoleum: { dataset: 'funerary' },
  bridge: { dataset: 'infrastructure' },
  road: { dataset: 'infrastructure' },
  'road-station': { dataset: 'infrastructure' },
  pass: { dataset: 'infrastructure' },
  dam: { dataset: 'infrastructure' },
  lighthouse: { dataset: 'infrastructure' },
  bath: { dataset: 'infrastructure' },
  port: { dataset: 'infrastructure' },
  'legionary-fortress': { dataset: 'military' },
  fortification: { dataset: 'military' },
  watchtower: { dataset: 'military' },
  mine: { dataset: 'production' },
  press: { dataset: 'production' },
  workshop: { dataset: 'production' },
  findspot: { dataset: 'production' },
  shipwreck: { dataset: 'production' },
  monument: { dataset: 'funerary' },
}
