#!/usr/bin/env python3
"""Generate the atlas TS modules from taxonomy.json + chunk counts.

THE palette and THE kind list live in src/data/taxonomy.json; this script
derives everything the frontend needs from them:
  - src/data/datasetRegistry.ts  (one toggle per kind, family colors)
  - src/data/entities/atlas/index.ts (loader with one static import per chunk)

Run after build-entity-atlas.py (build-data.sh does). Never hand-edit the
generated files.
"""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "src" / "data"

TAX = json.load(open(DATA / "taxonomy.json"))
COUNTS = {k: v["count"] for k, v in
          json.load(open(DATA / "entities" / "atlas" / "chunks.json")).items()}

# category -> overall panel group ('_hidden' = drawn by another toggle)
GROUP = {"settlement": "_hidden", "cities": "Urban", "rural": "Economy",
         "military": "Military", "religious": "Religion",
         "funerary": "Religion", "production": "Economy",
         "infrastructure": "Infrastructure"}
# per-kind overrides: every road dataset lives together (Dominik 2026-07-11)
KIND_GROUP = {"road": "Roads", "road-station": "Roads", "bridge": "Roads",
              "pass": "Roads"}

ACTIVE = {"cities": "bg-amber-900/80 border-amber-600 text-amber-100 hover:bg-amber-800/80",
          "rural": "bg-lime-900/80 border-lime-700 text-lime-100 hover:bg-lime-800/80",
          "military": "bg-rose-900/80 border-rose-700 text-rose-100 hover:bg-rose-800/80",
          "religious": "bg-violet-900/80 border-violet-700 text-violet-100 hover:bg-violet-800/80",
          "funerary": "bg-purple-900/80 border-purple-700 text-purple-100 hover:bg-purple-800/80",
          "production": "bg-yellow-950/80 border-yellow-800 text-yellow-200 hover:bg-yellow-900/80",
          "infrastructure": "bg-sky-900/80 border-sky-700 text-sky-100 hover:bg-sky-800/80",
          "settlement": "bg-yellow-900/80 border-yellow-700 text-yellow-100 hover:bg-yellow-800/80"}

PLURAL = {"Mine / Quarry": "Mines & Quarries", "Dam / Reservoir": "Dams & Reservoirs",
          "City Wall": "City Walls", "Mountain Pass": "Mountain Passes",
          "Church": "Churches", "Circus": "Circuses", "Monastery": "Monasteries",
          "Cemetery": "Cemeteries", "Sanctuary": "Sanctuaries", "Press": "Presses"}


def plural(label):
    return PLURAL.get(label, label + "s")


def main():
    entries = []
    for kind, v in sorted(TAX["kinds"].items(), key=lambda kv: -COUNTS.get(kv[0], 0)):
        if COUNTS.get(kind, 0) == 0:
            continue
        cat = TAX["categories"][v["category"]]
        label = "Settlements" if kind == "settlement" else plural(v["label"])
        entries.append(f"""  {{
    id: '{kind}',
    label: '{label}',
    group: '{KIND_GROUP.get(kind, GROUP[v["category"]])}',
    file: '{kind}',
    color: '{cat["color"]}',
    fillColor: '{cat["fill"]}',
    minZoom: 5,
    temporalFilter: true,
    activeClass: '{ACTIVE[v["category"]]}',
    attribution: SITE_ATTRIBUTION,
  }},""")

    registry = f"""/**
 * Dataset registry — one entry per KIND from src/data/taxonomy.json
 * (Dominik 2026-07-11: the toggles ARE the things — Forts, Villas,
 * Temples, Mines — under the overall panel groups; no invented
 * intermediate categories). GENERATED by scripts/gen-atlas-modules.py
 * from taxonomy.json (kinds, labels, THE palette) + atlas chunk counts —
 * regenerate, don't hand-edit. group '_hidden' = drawn by another toggle
 * (settlement rides with the Settlements toggle), not listed in the panel.
 */

export interface DatasetConfig {{
  id: string
  label: string
  group: string
  /** atlas kind chunk under src/data/entities/atlas/ */
  file: string

  color: string
  fillColor: string

  minZoom: number
  maxSample?: number

  temporalFilter: boolean

  activeClass: string
  attribution?: string
}}

const SITE_ATTRIBUTION = 'Sites: vici.org (CC BY-SA) · DARE · Pleiades'

export const DATASET_REGISTRY: DatasetConfig[] = [
{chr(10).join(entries)}
]

export function getDataset(id: string): DatasetConfig | undefined {{
  return DATASET_REGISTRY.find((d) => d.id === id)
}}
"""
    (DATA / "datasetRegistry.ts").write_text(registry)

    kinds = sorted(k for k in TAX["kinds"] if COUNTS.get(k, 0) > 0)
    imports = "\n".join(f"  '{k}': () => import('./{k}.json?raw')," for k in kinds)
    cats = ",\n".join(f"  '{k}'" for k in kinds)
    loader = f"""/**
 * The entity atlas — one chunk per KIND (the toggles are the things).
 * Emitted from the entity table by scripts/build-entity-atlas.py using
 * src/data/taxonomy.json. GENERATED by scripts/gen-atlas-modules.py —
 * regenerate, don't hand-edit.
 */
import {{ loadJsonRaw }} from '@/data/loadJson'

export interface AtlasEntity {{
  /** entity id — the knowledge-features lookup key */
  i: string
  /** cross-ref detail key when it differs from i (node ids resolve via knowledge-places) */
  d?: string
  /** display name (absent on unnamed survey points) */
  n?: string
  /** kind: fort, temple, villa, shipwreck, ... */
  k: string
  /** subtype where present: amphora cargo, gold, ... */
  st?: string
  la: number
  lo: number
  /** attestation window — only when a source attests it */
  s?: number
  e?: number
  /** 1 knowledge-bearing · 2 named · 3 unnamed texture */
  t: 1 | 2 | 3
  /** provenance codes — see SOURCE_LABELS in AtlasLayer */
  p?: string
}}

export const ATLAS_CATEGORIES = [
{cats},
] as const

export type AtlasCategory = (typeof ATLAS_CATEGORIES)[number]

const CHUNKS: Record<AtlasCategory, () => Promise<{{ default: string }}>> = {{
{imports}
}}

/** Load one kind chunk — the dataset-toggle loader. */
export async function loadAtlasCategory(category: string): Promise<AtlasEntity[]> {{
  const loader = CHUNKS[category as AtlasCategory]
  if (!loader) throw new Error(`Unknown atlas kind: ${{category}}`)
  return loadJsonRaw<AtlasEntity[]>(loader)
}}

/** Load selected kinds (defaults to all), in parallel chunks. */
export async function loadAtlasEntities(
  categories?: AtlasCategory[],
): Promise<Map<AtlasCategory, AtlasEntity[]>> {{
  const keys = categories ?? [...ATLAS_CATEGORIES]
  const parts = await Promise.all(keys.map((k) => loadJsonRaw<AtlasEntity[]>(CHUNKS[k])))
  return new Map(keys.map((k, idx2) => [k, parts[idx2]]))
}}
"""
    (DATA / "entities" / "atlas" / "index.ts").write_text(loader)
    print(f"generated datasetRegistry.ts ({len(entries)} kinds) + atlas/index.ts")


if __name__ == "__main__":
    main()
