#!/usr/bin/env python3
"""Profile every source vocabulary that feeds the entity table.

Phase-2 step 1 of the taxonomy pass (2026-07-11): before collapsing five
type vocabularies into ONE controlled kind list (src/data/taxonomy.json),
cross-tab what each source actually says. Output: docs/taxonomy-profile.md
(checked in — the evidence the taxonomy was designed against).
"""

import json
from collections import Counter
from pathlib import Path

DATA = Path(__file__).resolve().parent.parent / "src" / "data"
OUT = Path(__file__).resolve().parent.parent / "docs" / "taxonomy-profile.md"

DARE_LABELS = {11: 'Major Settlement', 12: 'Settlement', 13: 'Civitas Capital', 14: 'Villa',
               15: 'Village', 16: 'Road Station', 17: 'Legionary Fortress', 18: 'Fort',
               19: 'Farm/Rural', 21: 'Monastery', 24: 'Church', 31: 'Oppidum', 32: 'Tumulus',
               34: 'Arch/Trophy', 35: 'Late Roman Fortification', 43: 'Temple', 46: 'Bath',
               47: 'Aqueduct', 49: 'Pass', 50: 'Mausoleum', 51: 'Bridge', 52: 'Dam',
               53: 'Fortlet/Tower', 55: 'Road/Milestone', 57: 'Mine/Quarry',
               58: 'Kiln/Workshop', 61: 'Sanctuary', 63: 'Cemetery', 64: 'Monument',
               66: 'Findspot', 76: 'Lighthouse'}


def md_table(title, counter, label=lambda k: str(k), limit=60):
    lines = [f"\n## {title}\n", "| value | count |", "|---|---|"]
    for k, n in counter.most_common(limit):
        lines.append(f"| {label(k)} | {n} |")
    total = sum(counter.values())
    lines.append(f"| **total** | **{total}** |")
    return "\n".join(lines)


def date_stats(rows, get_start, get_end):
    n = len(rows)
    s = sum(1 for r in rows if get_start(r) not in (None, 0))
    e = sum(1 for r in rows if get_end(r) not in (None, 0))
    return f"{n} rows · start attested {s} ({100*s//max(n,1)}%) · end attested {e} ({100*e//max(n,1)}%)"


def main():
    sections = ["# Taxonomy profile — source vocabularies\n",
                "Generated by scripts/profile-taxonomy.py. The evidence base for",
                "src/data/taxonomy.json (one controlled kind list, category rollup).\n"]

    # vici siteType
    vici_rows = []
    idx = json.load(open(DATA / "vici" / "chunks.json"))
    c = Counter()
    for t, info in idx.items():
        rows = json.load(open(DATA / "vici" / info["file"]))
        c[t] = len(rows)
        vici_rows += rows
    sections.append(md_table("vici siteType", c))
    sections.append("\nDates: " + date_stats(vici_rows, lambda r: r.get("startYear"), lambda r: r.get("endYear")))

    # DARE type (places.json nodes)
    places = json.load(open(DATA / "places" / "places.json"))
    c = Counter((p.get("dare") or {}).get("type") for p in places)
    sections.append(md_table("DARE type (places.json)", c,
                             label=lambda k: f"{k} {DARE_LABELS.get(k, '?')}" if k else "(untyped node)"))
    sections.append("\nDates: " + date_stats(places, lambda r: r.get("startYear"), lambda r: r.get("endYear")))

    # unified type/subtype
    for f in sorted((DATA / "unified").glob("*.json")):
        rows = json.load(open(f))
        c = Counter((r.get("type"), r.get("subtype")) for r in rows)
        sections.append(md_table(f"unified/{f.name} type·subtype", c,
                                 label=lambda k: f"{k[0]} · {k[1] or '—'}"))
        sections.append("\nDates: " + date_stats(rows, lambda r: r.get("startYear"), lambda r: r.get("endYear")))

    # entity-table kinds (post-union view)
    table = json.load(open(DATA / "entities" / "entity-table.json"))
    c = Counter(e["kind"] for e in table)
    sections.append(md_table("entity-table kind (current union)", c))
    sections.append("\nDates: " + date_stats(table, lambda r: r.get("attestedFrom"), lambda r: r.get("attestedTo")))

    # QID coverage (P31 mining potential)
    qids = sum(1 for e in table if e.get("qid"))
    sections.append(f"\n## QID coverage\n\n{qids} of {len(table)} table rows carry a QID "
                    f"({100*qids//len(table)}%) — the P31 mining surface.")

    OUT.write_text("\n".join(sections) + "\n")
    print(f"wrote {OUT} ({OUT.stat().st_size // 1024} KB)")


if __name__ == "__main__":
    main()
