/**
 * The entity atlas — one chunk per KIND (the toggles are the things).
 * Emitted from the entity table by scripts/build-entity-atlas.py using
 * src/data/taxonomy.json. GENERATED by scripts/gen-atlas-modules.py —
 * regenerate, don't hand-edit.
 */
import { loadJsonRaw } from '@/data/loadJson'

export interface AtlasEntity {
  /** entity id — the knowledge-features lookup key */
  i: string
  /** cross-ref detail key when it differs from i (node ids resolve via knowledge-places) */
  d?: string
  /** display name (absent on unnamed survey points) */
  n?: string
  /** kind: fort, temple, villa, shipwreck, ... */
  k: string
  /** subtype where present: amphora cargo, gold, ... */
  st?: string
  la: number
  lo: number
  /** attestation window — only when a source attests it */
  s?: number
  e?: number
  /** 1 knowledge-bearing · 2 named · 3 unnamed texture */
  t: 1 | 2 | 3
  /** provenance codes — see SOURCE_LABELS in AtlasLayer */
  p?: string
}

export const ATLAS_CATEGORIES = [
  'amphitheater',
  'aqueduct',
  'basilica',
  'bath',
  'bridge',
  'building',
  'camp',
  'cemetery',
  'church',
  'circus',
  'cistern',
  'dam',
  'farm',
  'fort',
  'fortification',
  'forum',
  'gate',
  'lighthouse',
  'mausoleum',
  'mine',
  'monastery',
  'monument',
  'palace',
  'pass',
  'port',
  'press',
  'pyramid',
  'road',
  'road-station',
  'sanctuary',
  'settlement',
  'shipwreck',
  'temple',
  'theater',
  'tomb',
  'townhouse',
  'tumulus',
  'villa',
  'wall',
  'watchtower',
  'workshop',
] as const

export type AtlasCategory = (typeof ATLAS_CATEGORIES)[number]

const CHUNKS: Record<AtlasCategory, () => Promise<{ default: string }>> = {
  amphitheater: () => import('./amphitheater.json?raw'),
  aqueduct: () => import('./aqueduct.json?raw'),
  basilica: () => import('./basilica.json?raw'),
  bath: () => import('./bath.json?raw'),
  bridge: () => import('./bridge.json?raw'),
  building: () => import('./building.json?raw'),
  camp: () => import('./camp.json?raw'),
  cemetery: () => import('./cemetery.json?raw'),
  church: () => import('./church.json?raw'),
  circus: () => import('./circus.json?raw'),
  cistern: () => import('./cistern.json?raw'),
  dam: () => import('./dam.json?raw'),
  farm: () => import('./farm.json?raw'),
  fort: () => import('./fort.json?raw'),
  fortification: () => import('./fortification.json?raw'),
  forum: () => import('./forum.json?raw'),
  gate: () => import('./gate.json?raw'),
  lighthouse: () => import('./lighthouse.json?raw'),
  mausoleum: () => import('./mausoleum.json?raw'),
  mine: () => import('./mine.json?raw'),
  monastery: () => import('./monastery.json?raw'),
  monument: () => import('./monument.json?raw'),
  palace: () => import('./palace.json?raw'),
  pass: () => import('./pass.json?raw'),
  port: () => import('./port.json?raw'),
  press: () => import('./press.json?raw'),
  pyramid: () => import('./pyramid.json?raw'),
  road: () => import('./road.json?raw'),
  'road-station': () => import('./road-station.json?raw'),
  sanctuary: () => import('./sanctuary.json?raw'),
  settlement: () => import('./settlement.json?raw'),
  shipwreck: () => import('./shipwreck.json?raw'),
  temple: () => import('./temple.json?raw'),
  theater: () => import('./theater.json?raw'),
  tomb: () => import('./tomb.json?raw'),
  townhouse: () => import('./townhouse.json?raw'),
  tumulus: () => import('./tumulus.json?raw'),
  villa: () => import('./villa.json?raw'),
  wall: () => import('./wall.json?raw'),
  watchtower: () => import('./watchtower.json?raw'),
  workshop: () => import('./workshop.json?raw'),
}

/** Load one kind chunk — the dataset-toggle loader. */
export async function loadAtlasCategory(category: string): Promise<AtlasEntity[]> {
  const loader = CHUNKS[category as AtlasCategory]
  if (!loader) throw new Error(`Unknown atlas kind: ${category}`)
  return loadJsonRaw<AtlasEntity[]>(loader)
}

/** Load selected kinds (defaults to all), in parallel chunks. */
export async function loadAtlasEntities(
  categories?: AtlasCategory[],
): Promise<Map<AtlasCategory, AtlasEntity[]>> {
  const keys = categories ?? [...ATLAS_CATEGORIES]
  const parts = await Promise.all(keys.map((k) => loadJsonRaw<AtlasEntity[]>(CHUNKS[k])))
  return new Map(keys.map((k, idx2) => [k, parts[idx2]]))
}
